---
general:
  buildTool: "mta"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true
  Additional Unit Tests:
    steps:
      testmarcao: 
        sh 'uname -a'
    npmExecuteScripts: false
    karmaExecuteTests: false
  Acceptance:
    cloudFoundryDeploy: false
    cfApiEndpoint: "https://api.cf.sap.hana.ondemand.com"
    cfOrg: "COELAC_dev-env"
    cfSpace: "MALDAY"
    cfAppName: "DevOpsBTP"
    cfCredentialsId: "deploy-to-cf"
    uiVeri5ExecuteTests: false
  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.sap.hana.ondemand.com"
    cfOrg: "COELAC_dev-env"
    cfSpace: "MALDAY"
    cfAppName: "DevOpsBTP"
    cfCredentialsId: "deploy-to-cf"
    tmsUpload: true
steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  npmExecuteLint:
    failOnError: true
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  tmsUpload:
    nodeName: "DEV"
    credentialsId: "cicd-ctms"
  

